export const TerminateTaskParameters = [
    {
      id: 0,
      key: "name",
      value: "",
      changed: false,
      required: true,
      type: "string",
    },
    {
      id: 1,
      key: "taskReferenceName",
      value: "",
      changed: false,
      required: true,
    },
    {
      id: 2,
      key: "description",
      value: "",
      changed: false,
      required: false,
      type: "string",
    },
    {
      id: 3,
      key: "asyncComplete",
      value: false,
      changed: false,
      required: false,
      type: "boolean",
    },
    {
      id: 4,
      key: "startDelay",
      value: 0,
      changed: false,
      required: false,
      type: "int",
    },
    {
      id: 5,
      key: "rateLimited",
      value: false,
      changed: false,
      required: false,
      type: "boolean",
    },
    {
      id: 6,
      key: "retryCount",
      value: 0,
      changed: false,
      required: false,
      type: "int",
    },
  ];