name: CI - debug github
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install
        
      - name: Browser Cmd
        run: yarn add update-browserslist-db
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          component: true
#           browser: chrome
        env:
          DEBUG: '@cypress/github-action'
          
      
